# Generated by Django 4.2.15 on 2024-09-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_coupon_hotel_rating_hotel_state_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('deluxe', 'Deluxe'), ('super_deluxe', 'Super Deluxe'), ('suite', 'Suite')], max_length=50),
        ),
    ]
