# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JscgOaj5M6Wju2z0DnH1NSE581oT6wKF

create a quiz program using class object
"""

class Question:
    def __init__(self, prompt, answer): # Fixed the typo here
        self.prompt = prompt
        self.answer = answer

questions = [Question("What is 9 + 1?\n(a) 3\n(b) 10\n(c) 5\n\n", "b")]

score = 0
for question in questions:
    if input(question.prompt).lower() == question.answer:
        score += 1
        print("Correct!\n")
    else:
        print("Wrong!\n")

print(f"Your final score is: {score}/{len(questions)}")

"""create a calculator program using class object"""

class Calculator:
    def add(self, a, b):
        return a + b
    def subtract(self, a, b):
        return a - b
    def multiply(self, a, b):
        return a * b
    def divide(self, a, b):
        if b == 0:
            return "Error: Division by zero"
        return a / b
calc = Calculator()

print("Addition:", calc.add(5, 3))
print("Subtraction:", calc.subtract(5, 3))
print("Multiplication:", calc.multiply(5, 3))